[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
bytecode_hash = "none"
ffi = true
memory_limit = 268435456

# Required for Uniswap v4 hooks
via_ir = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./"}]

# Higher contract size limit for hooks
size_limit = 40000

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
